### ISSUE TITLE
Errors when trying to run

### ISSUE THREAD

**Issue by czegi90** [openwms/org.openwms.projects.humbolt#1]
Errors when trying to run on win10 with the following command:
docker-compose pull && docker-compose up.

I attached the log files, it might help to investigate:
[console-log.txt](https://github.com/openwms/org.openwms.projects.humbolt/files/6132316/console-log.txt)
[BOOT-WMS-Inventory.log](https://github.com/openwms/org.openwms.projects.humbolt/files/6132319/BOOT-WMS-Inventory.log)
[BOOT-CORE-UAA.log](https://github.com/openwms/org.openwms.projects.humbolt/files/6132320/BOOT-CORE-UAA.log)
[BOOT-CORE-Printing.log](https://github.com/openwms/org.openwms.projects.humbolt/files/6132321/BOOT-CORE-Printing.log)
[BOOT-CORE-Gateway.log](https://github.com/openwms/org.openwms.projects.humbolt/files/6132322/BOOT-CORE-Gateway.log)
[BOOT-COMMON-Service.log](https://github.com/openwms/org.openwms.projects.humbolt/files/6132323/BOOT-COMMON-Service.log)

**Comment by openwms** [comment]
All services are starting up at ones. As soon as the Service Registry (srv) is up and running all services do register themselves there. The second one is the Configuration Service (cfg). When both are up and running all other services startup successfully. If these two are not already up, all others are restarting over and over again. Normal behavior.
